apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-basm
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/basm`)
    kind: Rule
    services:
    - name: basm-demo-helm-chart
      port: 8000