---
all:
  children:
    linux:
      hosts:
        rp5.cluster:
          ansible_host: 192.168.8.10
          network:
            ipv4: 192.168.8.10
            interface: eth0
          arch: arm64
        rp3b.cluster:
          ansible_host: 192.168.8.11
          network:
            ipv4: 192.168.8.11
            interface: eth0
          arch: arm64
        sfvf2lite.cluster:
          ansible_host: 192.168.8.12
          network:
            ipv4: 192.168.8.12
            interface: end0
          arch: riscv64
    k0s:
      hosts:
        rp5.cluster:
        rp3b.cluster:
        sfvf2lite.cluster:
    k0s_init:
      hosts:
        sfvf2lite.cluster:
    k0s_controller:
      hosts:
        rp5.cluster:
        rp3b.cluster:
        sfvf2lite.cluster:
    k0s_worker:
